# Generated by Django 4.2.6 on 2023-11-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krei_markon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='designs',
            table='designs',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
